<? $comments = $this->article->getComments($this->commentsPage) ?>
<div class="clear"></div>
<a name="comments"></a>
<div id="comments">
<? if ($comments && count($comments)): ?>
<h3>Комментарии</h3>
<? drawPager($this, $comments, true) ?>
<ol class="comments" start="<?=$this->article->items_per_page*($this->commentsPage - 1)+1?>">
    <? foreach ($comments as $comment): ?>
    <li>
        <h4><?=$comment->title?><small><?=Filter_Date::timeAgo($comment->created)?></small>
        <? if ($comment->username): ?><span class="author">от <? if ($comment->email): ?><a href="mailto:<?=$comment->email?>"><?=$comment->username?></a><? else: ?><strong><?=$comment->username?></strong><? endif ?></span><? endif ?>
        </h4>
        <p><?=$comment->content?></p>
    </li>
    <? endforeach ?>
</ol>
<? endif ?>
<h4>Написать комментарий</h4>
<form method="post" action="#">
    <ol>
        <li><?=$this->input("comment_username", $this->newComment->username, "Ваше имя", 1)?></li>
        <li<? if ($this->errors['email']): ?> class="error"<? endif ?>><?=$this->input("comment_email", $this->newComment->email, "Электропочта", 1)?><? if ($this->errors['email']): ?><div class="error">Проверьте почтовый адрес, а то он не похож на настоящий.</div><? endif ?></li>
        <li><?=$this->input("comment_title", $this->newComment->title, "Тема", 1)?></li>
        <li<? if ($this->errors['content']): ?> class="error"<? endif ?>><?=$this->input("comment_content", $this->newComment->content, "Сообщение", 5)?><? if ($this->errors['content']): ?><div class="error">Вы не написали сообщение. Напишите его сейчас!</div><? endif ?></li>
        <li><?=$this->input("comment_url", "", "Не заполняйте это поле, пожалуйста", 1)?></li>
		<li><input type="submit" value="Написать" class="submit" /><input type="hidden" name="comment" value="save" /></li>
    </ol>
    <?/*=$this->tinymce()*/?>
    <script type="text/javascript">
    $(function () {
        $("input#comment_url").parent().css("display", "none");
        $("#comment_content").change(function () {
            $("input[type='submit']").attr("disabled", (this.value == "")? "disabled": "").focus();
        }).change();
        var $errors = $("li.error input,li.error textarea")
        if ($errors.length > 0) $errors.get(0).focus();
    });
    </script>
</form>
</div>

