<!--noindex-->
</div>
<div class="clear"></div>
<div id="footer">
    <ul class="validators">
		<li><a class="ibutton iblue" href="http://validator.w3.org/check?uri=referer" title="Valid XHTML 1.0 Strict"><em>W3C</em>XHTML 1.0</a></li>
		<li><a class="ibutton iblue" href="http://jigsaw.w3.org/css-validator/check/referer" title="Valid CSS!"><em>W3C</em>CSS</a></li>
    </ul>
    <ul class="copyright">
        <li>&copy; 2009 <a href="mailto:vostorg@tut.by">Анастасия Валицкая</a></li>
        <li>Дизайн и программирование &mdash; &copy; 2009 <a href="mailto:kstep@p-nut.info">Константин Степанов</a></li>
    </ul>
</div>
</div>
<!--/noindex-->
</body>
</html>
