<? $this->title = "Правка комментария" ?>
<? $this->topicId = $this->comment->topic ?>
<? $this->breadcrumb = array(
	$this->pathTo("Topic", "default") => "Контент",
	$this->pathTo("Topic", "default", array( "id" => $this->comment->getArticle()->topic )) => "Раздел &laquo;".$this->comment->getArticle()->getTopic()->title."&raquo;",
	$this->pathTo("Article", "edit", array( "id" => $this->comment->article )) => "Статья &laquo;".$this->comment->getArticle()->title."&raquo;",
	$this->pathTo("User", "edit", array( "id" => $this->comment->author )) => "Пользователь ".($this->comment->author? "&laquo;".$this->comment->getAuthor()->username."&raquo;": "&laquo;{$this->comment->username}&raquo;"),
	"" => "Комментарий &laquo;".$this->comment->title."&raquo;"
) ?>
<? include("header.phtml") ?>

<div id="navigation">
<? include("nav_topics.phtml") ?>
</div>

<div id="contents">
<? if ($this->comment->getId()): ?>
<h2>Комментарий &laquo;<?=$this->comment->title?>&raquo;</h2>
<? else: ?>
<h2>Новый комментарий</h2>
<? endif ?>

<form action="#" method="post">
<?=$this->hidden("article", $this->comment->article)?>
<ol>
    <?li($this, 'title')?><?=$this->input("title", $this->comment->title, "Заголовок")?></li>
    <?li($this, 'content')?><?=$this->input("content", $this->comment->content, "Содержание", 10)?></li>
    <?li($this, 'username')?><?=$this->input("username", $this->comment->username, "Имя автора")?></li>
    <?li($this, 'email')?><?=$this->input("email", $this->comment->email, "Электропочта")?></li>
    <li id="options">
        <fieldset>
            <legend>Опции</legend>
            <ol class="checklist">
                <li class="checklist"><?=$this->checklist("flags", array( "hidden" => "Скрыт", "removed" => "В корзине" ), false, $this->comment->flags)?></li>
            </ol>
        </fieldset>
    </li>
    <li id="timestamps">
        <fieldset>
            <legend>Когда</legend>
            <ol>
                <li>&hellip;создан <?=Filter_Date::toString($this->comment->created)?>.</li>
                <li>&hellip;изменен <?=Filter_Date::toString($this->comment->modified)?>.</li>
            </ol>
        </fieldset>
    </li>
    <li id="submit">
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Сбросить" />
        <input type="hidden" name="save" value="1" />
    </li>
</ol>
</form>

<?=$this->tinymce()?>
</div>
<? include("footer.phtml") ?>
