</div><!--/body-->

<div id="footer">
	<ul id="validators">
		<li><a href="http://validator.w3.org/check?uri=referer"><img src="<?=$this->_prefix?>/static/images/valid/valid-xhtml10-blue.png" alt="Valid XHTML 1.0 Strict" title="Valid XHTML 1.0 Strict" /></a></li>
		<li><a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="<?=$this->_prefix?>/static/images/valid/vcss-blue.gif" alt="Valid CSS!" title="Valid CSS!" /></a></li>
	</ul>

	<ul id="copyrights">
		<li>&copy; 2009 <a href="mailto:kstep@p-nut.info">Константин Степанов</a></li>
	</ul>
</div><!--/footer-->
</div><!--/wrapper-->
</body>
</html>
