<?$this->charset("utf-8")?>
<?=$this->doctype("xhtml")?>
<?
	function li($me, $name, $tag = "li")
	{
		echo "<$tag";
		if ($me->errors[$name])
		{
			?> class="error"><div class="error"><?=$me->errors[$name]?></div<?
		}
		?>><?
	}
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
	<title>p-nut &mdash; Панель управления</title>
	<?=$this->meta("Content-Type", "text/html; charset=UTF-8", true)?>

    <link rel="icon" href="<?=$this->_prefix?>/static/images/pfavicon.ico" type="image/x-icon" />
	<?=$this->style("style")?>
	<?=$this->style("navigation")?>
	<?=$this->style("forms")?>
	<?=$this->style("form")?>

    <script type="text/javascript">
        var sitePrefix = "<?=addslashes($this->_prefix) ?>";
    </script>
    <?=$this->script("tinymce/tiny_mce")?>
    <?=$this->script("lib/jquery/core")?>
    <?=$this->script("lib/jquery/ui")?>
</head>
<body>
<div id="wrapper">
<div id="header">
	<h1><a href="<?=$this->_prefix?>">p-nut<small>.manage</small></a></h1>
	<ul id="topmenu" class="menu">
		<li><a href="<?=$this->pathTo('Topic', 'default')?>">Контент</a></li>
		<li><a href="<?=$this->pathTo('Poll', 'default')?>">Опросы</a></li>
		<li><a href="<?=$this->pathTo('Tag', 'default')?>">Теги</a></li>
		<li><a href="<?=$this->pathTo('Group', 'default')?>">Пользователи</a></li>

		<li class="right"><a href="#manage">Выйти</a></li>
		<li class="separator right"><a href="#manage">Вы зашли как <strong style="text-transform: capitalize;"><?=$_SERVER['PHP_AUTH_USER']?></strong></a></li>
	</ul>
	<ul id="breadcrumb">
		<li><a href="#">Контент</a></li>
		<li>Разделы</li>
	</ul>
</div>
<div id="body">

