<?
$this->title = "Список разделов";
$this->topicId = $this->topic? $this->topic->getId(): 0;
?>
<? include("header.phtml") ?>
<div id="navigation">
<? include("nav_topics.phtml") ?>
</div>
<div id="contents">
<div id="articles">
<? if ($this->topic): ?>
	<h2>Статьи из раздела &laquo;<?=$this->topic->title?>&raquo; <small>(<?=$this->topic->name?>)</small></h2>
	<div class="description"><?=$this->topic->description?></div>
    <table class="itemsList" summary="Статьи из раздела">
		<thead>
		<tr><th style="width: 2em;">№</th><th>Заголовок</th><th>Название</th><th>Создана</th><th>Изменена</th><th>&nbsp;</th></tr>
		</thead>
		<tbody>
    <? foreach ($this->topic->getArticles() as $item): ?>
		<tr id="a<?=$item->getId()?>" class="<?=$item->type?> <?=implode(" ", $item->flags)?>"><td><?=$item->order?></td><td><a href="<?=$this->pathTo("Admin_Article", "edit", array( 'id' => $item->getId() ))?>"><?=$item->title?></a></td><td><?=$item->name?></td><td><?=date("d.m.Y H:i", $item->created)?></td><td><?=date("d.m.Y H:i", $item->modified)?></td><td><a class="remove" href="<?=$this->pathTo("Admin_Article", "remove", array( 'id' => $item->getId() ))?>">&nbsp;</a></td></tr>
    <? endforeach ?>
        <tr id="anew"><td colspan="6"><a class="add" href="<?=$this->pathTo("Admin_Article", "new", array( 'id' => $this->topic->getId() ))?>">Новая статья</a></td></tr>
		</tbody>
    </table>
	<script type="text/javascript">$("table tbody tr:odd").addClass("odd");</script>
<? else: ?>
	<h2>Статей в этом разделе нет</h2>
<? endif ?>
</div>

</div>

<? include("footer.phtml") ?>
