<div id="groups" class="moduleBox">
<h2>Группы</h2>
<ul>
	<? foreach ($this->groups as $group): ?>
    <? if ($this->groups->getStep() > 0): ?><?=str_repeat("<ul>", $this->groups->getStep())?><? elseif ($this->groups->getStep() < 0): ?><?=str_repeat("</li></ul></li>", -($this->groups->getStep()))?><? elseif (!$this->groups->isFirst()): ?></li><? endif ?>
    <li id="g<?=$group->getId()?>"<? if ($group->getId() == $this->groupId): ?> class="active"<?endif?>>
        <a href="<?=$this->pathTo("Admin_Group", "default", array( 'id' => $group->getId() ))?>"><?=$group->title?></a> <small>(<?=$group->name?>)</small>
	<? endforeach ?>
	<? if ($this->groups->getLevel() > 1): ?><?=str_repeat("</li></ul></li>", $this->groups->getLevel()-1)?><? endif ?>
</ul>
</div>
