<div id="topics" class="moduleBox">
<h2>Разделы</h2>
<ul>
<? foreach ($this->topics as $topic): ?>
    <? if ($this->topics->getStep() > 0): ?><?=str_repeat("<ul>", $this->topics->getStep())?><? elseif ($this->topics->getStep() < 0): ?><?=str_repeat("</li></ul></li>", -($this->topics->getStep()))?><? elseif (!$this->topics->isFirst()): ?></li><? endif ?>
    <li id="t<?=$topic->getId()?>"<? if ($topic->getId() == $this->topicId): ?> class="active"<?endif?>>
		<a href="<?=$this->pathTo("Admin_Topic", "default", array( 'id' => $topic->getId() ))?>"><?=$topic->title?></a> <small>(<?=$topic->name?>)</small>
<? endforeach ?>
	<? if ($this->topics->getLevel() > 1): ?><?=str_repeat("</li></ul></li>", $this->topics->getLevel()-1)?><? endif ?>
    </li>
</ul>
</div>
