<? $this->modified($this->article) ?>
<? $this->title = $this->article->title . " &mdash; Шаблон сайта" ?>
<?
$this->topicId = $this->article->topic;
$this->rootTopicId = $this->rootTopic->getId();
?>
<? include("header.phtml") ?>

<div id="content">
    <h1><?=$this->article->title ?><span class="date"><?=Filter_Date::timeAgo($this->article->modified)?></span></h1>
    <div class="abstract"><?=$this->article->abstract ?></div> 
    <? if ($this->article->type == 'article'): ?>
        <?=$this->article->content ?>
    <? else: ?>
        <? include("gallery.phtml") ?>
    <? endif ?>
    <? if (in_array("comments", $this->article->flags)): include("comments.phtml"); endif ?>

</div>

<? include("footer.phtml") ?>
