</div><!--/body-->

<div id="footer">
	<ul id="validators">
		<li><a class="ibutton iblue" href="http://validator.w3.org/check?uri=referer" title="Valid XHTML 1.0 Strict"><em>W3C</em>XHTML 1.0</a></li>
		<li><a class="ibutton iblue" href="http://jigsaw.w3.org/css-validator/check/referer" title="Valid CSS!"><em>W3C</em>CSS</a></li>
	</ul>
	<ul id="copyrights">
		<li>&copy; 2009 <a href="mailto:kstep@p-nut.info">Константин Степанов</a></li>
	</ul>
</div><!--/footer-->
</div><!--/wrapper-->
</body>
</html>
