<?$this->charset("utf-8")?>
<?=$this->doctype("xhtml")?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
	<title>p-nut</title>
	<?=$this->meta("Content-Type", "text/html; charset=UTF-8", true)?>

    <script type="text/javascript">
        var sitePrefix = "<?=addslashes($this->_prefix) ?>";
    </script>
	<?=$this->style("style")?>
</head>
<body>
<div id="wrapper">
<div id="header">
	<h1><a href="<?=$this->_prefix?>">p-nut</a></h1>
	<ul id="topmenu" class="menu">
		<li><a href="#news">Новости</a></li>
		<li><a href="#blog">Блог</a></li>
		<li class="separator"><a href="#doc">Доки</a></li>
		<li><a href="#dload">Скачать</a></li>
		<li><a href="#git">Git</a></li>
		<li><a href="#bugs">Баги</a></li>
		<li class="separator"><a href="#pnut">О проекте</a></li>
		<li><a href="#whoami">Обо мне</a></li>
		<li><a href="#works">Портфолио</a></li>
		<li class="separator right"><a href="#manage">Админка</a></li>
	</ul>
	<ul id="breadcrumb">
		<li><a href="#">Блог</a></li>
		<li><a href="#">Теги</a></li>
		<li><a href="#">Языки</a></li>
		<li>PHP</li>
	</ul>
</div>
<div id="body">

