<?$this->charset("utf-8")?>
<?=$this->doctype("xhtml")?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
	<title>p-nut</title>
	<?=$this->meta("Content-Type", "text/html; charset=UTF-8", true)?>

    <script type="text/javascript">
        var sitePrefix = "<?=addslashes($this->_prefix) ?>";
    </script>
	<?=$this->style("common/style")?>
	<?=$this->style("common/colors")?>
    <link rel="icon" href="<?=$this->_prefix?>/static/images/favicon.ico" type="image/x-icon" />
</head>
<body>
<div id="wrapper">
<div id="header">
	<h1><a href="<?=$this->_prefix?>">p-nut</a></h1>
	<ul id="topmenu" class="menu">
		<li><a href="<?=$this->pathTo('Default', 'topic', array('path' => 'news'))?>">Новости</a></li>
		<li><a href="<?=$this->pathTo('Default', 'topic', array('path' => 'blog'))?>">Блог</a></li>
		<li class="separator"><a href="#doc">Доки</a></li>
		<li><a href="<?=$this->pathTo('Default', 'topic', array('path' => 'download'))?>">Скачать</a></li>
		<li><a href="http://git.p-nut.info/pnut.git">Git</a></li>
		<li><a href="#bugs">Баги</a></li>
		<li class="separator"><a href="#pnut">О проекте</a></li>
		<li><a href="#whoami">Обо мне</a></li>
		<li><a href="#works">Портфолио</a></li>
		<li class="separator right"><a class="secure" href="<?=$this->_prefix?>/manage">Админка</a></li>
	</ul>
	<ul id="breadcrumb">
		<li><a href="#">Блог</a></li>
		<li><a href="#">Теги</a></li>
		<li><a href="#">Языки</a></li>
		<li>PHP</li>
	</ul>
</div>
<div id="body">

