<div id="navigation">
    <? if ($this->rootTopic): ?>
    <? $iter = $this->rootTopic->getDescendants() ?>
    <? if ($iter): ?>
    <ul>
        <? foreach ($iter as $topic): ?>
        <? if ($iter->getStep() > 0): ?><?=str_repeat("<ul>", $iter->getStep())?><? elseif ($iter->getStep() < 0): ?><?=str_repeat("</li></ul>", -($iter->getStep()))?><? elseif (!$iter->isFirst()): ?></li><? endif ?>
        <li><?if ($this->topicId == $topic->getId()):?><strong><?if ($this->article):?><a href="<?=$this->pathTo('Default', 'topic', array( 'path' => $iter->getPath() ))?>/"><?=$topic->title?></a><?else:?><?=$topic->title?><?endif?></strong><?else:?><a href="<?=$this->pathTo('Default', 'topic', array( 'path' => $iter->getPath() ))?>/"><?=$topic->title?></a><?endif?>
        <? endforeach ?>
        <? if ($iter->getLevel() > 1): ?><?=str_repeat("</li></ul></li>", $iter->getLevel()-1)?><? endif ?>
    </ul>
    <? endif ?>
    <? endif ?>
</div>
