<? $this->title = "Правка вложения" ?>
<? $this->topicId = $this->attachment->topic ?>
<? $this->breadcrumb = array(
	$this->pathTo("Topic", "default") => "Контент",
	$this->pathTo("Topic", "default", array( "id" => $this->attachment->getArticle()->topic )) => "Раздел &laquo;".$this->attachment->getArticle()->getTopic()->title."&raquo;",
	$this->pathTo("Article", "edit", array( "id" => $this->attachment->article )) => "Статья &laquo;".$this->attachment->getArticle()->title."&raquo;",
	$this->pathTo("User", "edit", array( "id" => $this->attachment->author )) => "Пользователь &laquo;".$this->attachment->getAuthor()->username."&raquo;",
	"" => "Вложение &laquo;".$this->attachment->title."&raquo;",
) ?>
<? include("header.phtml") ?>

<div id="navigation">
<? include("nav_topics.phtml") ?>
</div>

<div id="contents">
<? if ($this->attachment->getId()): ?>
<h2>Вложение &laquo;<?=$this->attachment->title?>&raquo; <small>(<?=$this->attachment->filename?>)</small></h2>
<? else: ?>
<h2>Новое вложение</h2>
<? endif ?>

<form action="#" method="post" enctype="multipart/form-data">
<?=$this->hidden("article", $this->attachment->article)?>
<ol>
    <?li($this, 'title')?><?=$this->input("title", $this->attachment->title, "Заголовок")?></li>
    <?li($this, 'filename')?><?=$this->input("filename", $this->attachment->filename, "Имя файла")?></li>
    <?li($this, 'mimetype')?><?=$this->input("mimetype", $this->attachment->mimetype, "MIME-тип")?></li>
	<?li($this, 'attach')?><label for="attach">Заменить файлом</label><input type="file" name="attach" id="attach" /></li>

    <li id="information">
        <fieldset>
            <legend>Информация о файле</legend>
            <dl>
				<dt>Размер</dt><dd><?=Filter_File::humanizeSize($this->attachment->filesize)?> (<?=$this->attachment->filesize?> <?=Filter_Date::wordform($this->attachment->filesize, "байт", "байта", "байтов")?>)</dd>
				<dt>Хэш MD5</dt><dd><?=$this->attachment->md5hash?></dd>
				<dt>Расположен по пути</dt><dd><?=$this->attachment->getFilepath()?></dd>
				<dt>Статус</dt><dd><? if ($check = $this->attachment->checkFile()): ?>Файл исправен: <a href="<?=$this->pathTo('File', 'download', array( 'id' => $this->attachment->getId() ))?>">скачать</a> / <a href="<?=$this->pathTo('File', 'view', array( 'id' => $this->attachment->getId() ))?>">посмотреть</a><? elseif ($check === null): ?>Файл не найден.<? else: ?>Файл повреждён<? endif ?></dd>
				<? if ($check && $this->attachment->isImage()): ?>
				<? list($width, $height) = getimagesize($this->attachment->getFilepath()) ?>
				<dt>Размеры изображения</dt><dd><?=$width?>x<?=$height?></dd>
				<dt>Миниатюра</dt><dd><img src="<?=$this->pathTo('Image', 'thumbnail', array( 'id' => $this->attachment->getId(), 'scale' => 200 ))?>" /></dd>
				<? endif ?>
            </dl>
			<?stripe("dl dd:odd, dl dt:odd")?>
        </fieldset>
    </li>

	<? //show_rights($this, $this->attachment) ?>

    <li id="timestamps">
        <fieldset>
            <legend>Когда</legend>
            <ol>
                <li>&hellip;создано <?=Filter_Date::toString($this->attachment->created)?>.</li>
                <li>&hellip;изменено <?=Filter_Date::toString($this->attachment->modified)?>.</li>
            </ol>
        </fieldset>
    </li>

    <li id="submit">
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Сбросить" />
        <input type="hidden" name="save" value="1" />
    </li>
</ol>
</form>

<?=$this->tinymce()?>
</div>
<? include("footer.phtml") ?>
