<? $this->title = "Правка группы" ?>
<? $this->groupId = $this->group->getId() ?>
<? include("header.phtml") ?>

<div id="navigation">
<? include("nav_groups.phtml") ?>
</div>

<div id="contents">
<? if ($this->group->getId()): ?>
<h2>&laquo;<?=$this->group->title?>&raquo; <small>(<?=$this->group->name?>)</small></h2>
<? else: ?>
<h2>Новая группа</h2>
<? endif ?>

<form action="#" method="post">
<ol>
    <?li($this, 'title')?><?=$this->input("title", $this->group->title, "Заголовок")?></li>
    <?li($this, 'name')?><?=$this->input("name", $this->group->name, "Название")?></li>
	<?li($this, 'role')?><?=$this->select("role", array('guest' => 'Гость', 'user' => 'Пользователь', 'manager' => 'Менеджер', 'admin' => 'Администратор', 'superuser' => 'Суперпользовтатель'), $this->group->role, "Роль")?></li>
	<?li($this, 'parent')?><?=$this->select("parent", $this->parents, $this->group->parent, "Родитель", "root")?></li>

    <li id="submit">
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Сбросить" />
        <input type="hidden" name="save" value="1" />
    </li>
</ol>
</form>

</div>
<? include("footer.phtml") ?>
