<? $this->title = "Правка статьи" ?>
<? $this->topicId = $this->article->topic ?>
<? $this->breadcrumb = array(
	$this->pathTo("Topic", "default") => "Контент",
	$this->pathTo("Topic", "default", array( "id" => $this->article->topic )) => "Раздел &laquo;".$this->article->getTopic()->title."&raquo;",
	"" => "Статья &laquo;".$this->article->title."&raquo;",
) ?>
<? include("header.phtml") ?>

<div id="navigation">
<? include("nav_topics.phtml") ?>
</div>

<div id="contents">
<? if ($this->article->getId()): ?>
<h2>&laquo;<?=$this->article->title?>&raquo; <small>(<?=$this->article->name?>)</small></h2>
<? else: ?>
<h2>Новая статья</h2>
<? endif ?>

<? $users = $this->users->fetchAll() ?>

<form action="#" method="post" enctype="multipart/form-data">
<ol>
    <?li($this, 'title')?><?=$this->input("title", $this->article->title, "Заголовок")?></li>
    <?li($this, 'name')?><?=$this->input("name", $this->article->name, "Название")?></li>
    <?li($this, 'abstract')?><?=$this->input("abstract", $this->article->abstract, "Резюме", 5)?></li>
    <?li($this, 'content')?><?=$this->input("content", $this->article->content, "Содержание", 20)?></li>
    <?li($this, 'type')?><?=$this->select("type", array( "article" => "Обычная статья", "gallery" => "Галерея" ), $this->article->type, "Тип статьи")?></li>
	<?li($this, 'author')?><?=$this->select('author', $this->users, $this->article->author, 'Автор')?></li>
    <li id="options">
        <fieldset>
            <legend>Опции</legend>
            <ol class="checklist">
                <li class="checklist"><?=$this->checklist("flags", array( "hidden" => "Скрыта", "archived" => "В архиве", "removed" => "В корзине", "comments" => "С комментариями" ), false, $this->article->flags)?></li>
				<?li($this, 'items_per_page')?><?=$this->input("items_per_page", $this->article->items_per_page, "Объекты/страница", 1, 5)?></li>
            </ol>
        </fieldset>
    </li>
    <li id="timestamps">
        <fieldset>
            <legend>Когда</legend>
            <ol>
                <li>&hellip;создана <?=Filter_Date::toString($this->article->created)?>.</li>
                <li>&hellip;изменена <?=Filter_Date::toString($this->article->modified)?>.</li>
                <?li($this, 'published')?><?=$this->input("published", Filter_Date::toString($this->article->published), "Опубликовать")?></li>
                <?li($this, 'archived')?><?=$this->input("archived", Filter_Date::toString($this->article->archived), "Поместить в архив")?></li>
            </ol>
        </fieldset>
    </li>
	<li id="localization">
		<fieldset>
			<legend>Локализация</legend>
			<ol>
				<?li($this, 'language')?><?=$this->input('language', $this->article->language, 'Язык', 1, 5)?></li>
				<?li($this, 'original')?><?=$this->select('original', $this->article->getTopic()->getArticles(), $this->article->original, 'Оригинал', '- отсутствует -')?></li>
			</ol>
		</fieldset>
	</li>

	<? //show_rights($this, $this->article) ?>

    <li id="attachments" class="table-view">
        <fieldset>
            <legend>Вложения <a href="#"><var class="table-title">в виде списка</var><var class="thumb-title">с миниатюрами</var></a></legend>
			<? include ('list_attachments.phtml') ?>
			<script type="text/javascript">$('#attachments legend a').click(function(){
				var $container = $(this.parentNode.parentNode.parentNode);
				$container.attr('class', $container.attr('class') == 'table-view'? 'thumb-view': 'table-view');
				return false;
			;})</script>
        </fieldset>
    </li>
    <? $comments = $this->article->getComments() ?>
    <? if ($comments && count($comments)): ?>
    <li id="comments">
        <fieldset>
            <legend>Комментарии</legend>
            <table class="item-list" summary="Комментарии к статье">
				<thead>
				<tr><th>Заголовок</th><th>Автор</th><th>Дата</th><th>&nbsp;</th></tr>
				</thead>
				<tbody>
                <? foreach ($comments as $item): ?>
                <tr id="c<?=$item->getId()?>"><td><a href="<?=$this->pathTo("Admin_Comment", "edit", array( 'id' => $item->getId() ))?>">&laquo;<?=$item->title?>&raquo;</a></td><td><? if ($item->email): ?><a href="mailto:<?=$item->email?>"><?=$item->username?$item->username:$item->email?></a><? else: ?><?=$item->username?><? endif ?></td><td><?=date("d.m.Y H:i", $item->created)?></td><td><a class="remove" href="<?=$this->pathTo("Admin_Comment", "remove", array( 'id' => $item->getId() ))?>" title="Удалить">&nbsp;</a></td></tr>
                <? endforeach ?>
				</tbody>
            </table>
        </fieldset>
    </li>
    <? endif ?>
    <li id="submit">
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Сбросить" />
        <input type="hidden" name="save" value="1" />
		<?=$this->hidden("topic", $this->article->topic)?>
    </li>
</ol>
</form>

<?=$this->tinymce()?>
<script type="text/javascript">
$('#title').blur(function () {
	var title = $('#title').val();
	var name = $('#name').val();
	if (name == '' && title != '')
	{
		title = title.replace(/[Аа]/g, 'a').replace(/[Бб]/g, 'b').replace(/[Вв]/g, 'v').replace(/[Гг]/g, 'g').replace(/[Дд]/g, 'd')
				.replace(/[Ее]/g, 'e').replace(/[Ёё]/g, 'e').replace(/[Жж]/g, 'zh').replace(/[Зз]/g, 'z').replace(/[Ии]/g, 'i')
				.replace(/[Йй]/g, 'j').replace(/[Кк]/g, 'k').replace(/[Лл]/g, 'l').replace(/[Мм]/g, 'm').replace(/[Нн]/g, 'n')
				.replace(/[Оо]/g, 'o').replace(/[Пп]/g, 'p').replace(/[Рр]/g, 'r').replace(/[Сс]/g, 's').replace(/[Тт]/g, 't')
				.replace(/[Уу]/g, 'u').replace(/[Фф]/g, 'f').replace(/[Хх]/g, 'h').replace(/[Цц]/g, 'c').replace(/[Чч]/g, 'ch')
				.replace(/[Шш]/g, 'sh').replace(/[Щщ]/g, 'sch').replace(/[Ыы]/g, 'y').replace(/[ЪъЬь]/g, '').replace(/[Ээ]/g, 'e')
				.replace(/[Юю]/g, 'yu').replace(/[Яя]/g, 'ya').replace(/[.:;, ]+/g, '_').replace(/[^A-Za-z_-]/g, '');
		$('#name').val(title);
	}
});
</script>
</div>
<? include("footer.phtml") ?>
