<form id="question" class="popup-form" action="#">
	<h3>&#8963; вопрос</h3>
	<ol>
		<li>&nbsp;</li>
		<li><input type="reset" value="Нет" class="reset" /><input type="submit" class="submit" value="Да" /></li>
	</ol>
</form>

<div id="error-form" class="error-form popup-form">
	<h3>Ошибка!</h3>
	<p>&nbsp;</p>
</div>

<?=$this->script("manage/popups_init")?>

</div><!--/body-->

<div id="footer">
	<ul id="validators">
		<li><a class="ibutton igreen" href="http://p-nut.info/" title="Powered by p-nut"><em>Powered by</em>p-nut</a></li>
		<li><a class="ibutton igreen" href="http://www.vim.org/" title="Made with VIM"><em>Made with</em>VIM</a></li>
		<li><a class="ibutton iblue" href="http://validator.w3.org/check?uri=referer" title="Valid XHTML 1.0 Strict"><em>W3C</em>XHTML 1.0</a></li>
		<li><a class="ibutton iblue" href="http://jigsaw.w3.org/css-validator/check/referer" title="Valid CSS!"><em>W3C</em>CSS</a></li>
	</ul>
	<ul id="copyrights">
		<li>&copy; 2009 <a href="mailto:kstep@p-nut.info">Константин Степанов</a></li>
	</ul>
</div><!--/footer-->
</div><!--/wrapper-->

</body>
</html>
