<?$this->charset("utf-8")?>
<?=$this->doctype("xhtml")?>
<?
	function li($me, $name, $tag = "li")
	{
		echo "<$tag";
		if ($me->errors[$name])
		{
			?> class="error"><div class="error"><?=$me->errors[$name]?></div<?
		}
		?>><?
	}

	function stripe($elems)
	{
		?><script type="text/javascript">$("<?=$elems?>").addClass("odd");</script><?
	}
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
	<title><?=$this->title?> &mdash; p-nut.manage &beta;</title>
	<?=$this->meta("Content-Type", "text/html; charset=UTF-8", true)?>

    <link rel="icon" href="<?=$this->_prefix?>/static/images/pfavicon.ico" type="image/x-icon" />
	<?=$this->style("common/style")?>
	<?=$this->style("common/forms")?>
	<?=$this->style("common/colors")?>
	<?=$this->style("navigation")?>

    <?=$this->script("tinymce/tiny_mce")?>
    <?=$this->script("lib/jquery/core")?>
    <?=$this->script("lib/jquery/ui")?>

    <script type="text/javascript">
        var sitePrefix = "<?=addslashes($this->_prefix) ?>";

		$(function() {
			$("fieldset > ol, fieldset > table, fieldset > dl").addClass("hidden");
			$("fieldset > legend").click(function (ev)
				{
					var $me = $(ev.target.parentNode);
					$me.find("ol, table, dl").toggleClass("hidden");
				}
			);
		});
    </script>
</head>
<body>
<div id="wrapper">
<div id="header">
	<h1><a href="<?=$this->_prefix?>">p-nut<small>.manage<sup>&beta;</sup></small></a></h1>
	<ul id="topmenu" class="menu">
		<li><a href="<?=$this->pathTo('Topic', 'default')?>">Контент</a></li>
		<li><a href="<?=$this->pathTo('Group', 'default')?>">Пользователи</a></li>
		<li><a href="#" class="notimplemented"><?//=$this->pathTo('Poll', 'default')?>Опросы</a></li>
		<li><a href="#" class="notimplemented"><?//=$this->pathTo('Tag', 'default')?>Теги</a></li>

		<li class="right"><a class="logout" href="#manage">Выйти</a></li>
		<li class="separator right"><a href="#manage">Вы зашли как <strong style="text-transform: capitalize;"><?=$_SERVER['PHP_AUTH_USER']?></strong></a></li>
	</ul>
	<ul id="breadcrumb">
		<? if ($this->breadcrumb): ?>
		<? foreach ($this->breadcrumb as $link => $title): ?>
		<? if ($link): ?>
		<li><a href="<?=$link?>"><?=$title?></a></li>
		<? else: ?>
		<li><?=$title?></li>
		<? endif ?>
		<? endforeach ?>
		<? else: ?>
		<li>Контент</li>
		<? endif ?>
	</ul>
</div>
<div id="body">

