<form id="rename-topic" class="popup-form" action="#">
	<h3>&#8963; переименовать</h3>
	<ol>
		<li><label for="ttitle">Заголовок</label><input type="text" value="" id="ttitle" name="title" /></li>
		<li><label for="tname">Название</label><input type="text" value="" id="tname" name="name" /></li>
		<li><input type="reset" value="Отмена" class="reset" /><input type="submit" value="ОК" class="submit" /></li>
	</ol>
</form>
