<table class="itemList" summary="Вложения в статье">
<thead>
<tr><th>Заголовок / имя файла</th><th>MIME-тип</th><th>Размер</th><th>Создано / изменено</th><th>&nbsp;</th></tr>
</thead>
<tbody>
	<? foreach ($this->article->getAttachments() as $item): ?>
	<tr id="f<?=$item->getId()?>"><td><img src="<?=$this->pathTo("Image", "thumbnail", array( 'id' => $item->getId(), 'scale' => 120 ))?>" alt="Миниатюра" /><a href="<?=$this->pathTo("Attachment", "edit", array( 'id' => $item->getId() ))?>"><?=$item->title?></a><br /><small><?=$item->filename?></small></td><td><?=$item->mimetype?></td><td><?=Filter_File::humanizeSize($item->filesize, 0)?></td><td><?=date("d.m.Y H:i", $item->created)?><br /><?=date("d.m.Y H:i", $item->modified)?></td><td><a href="<?=$this->pathTo("File", "download", array( 'id' => $item->getId() ))?>" title="Скачать" class="download">&nbsp;</a><a class="remove" href="<?=$this->pathTo("Article", "dettach", array( 'id' => $item->getId() ))?>" title="Удалить">&nbsp;</a></td></tr>
	<? endforeach ?>
	<tr><td colspan="5"><input type="file" name="attach[]" /></td><td><a class="remove" href="#" title="Убрать">&nbsp;</a></td></tr>
	<tr><td colspan="6"><a class="add" href="#">Добавить</a>&nbsp;<a href="#" class="add5" title="Добавить пять файлов">&#215;5</a></td></tr>
</tbody>
</table>
