<?
$this->title = "Список групп";
$this->groupId = $this->group? $this->group->getId(): 0;
?>
<?
$this->breadcrumb = $this->groupId? array(
	$this->pathTo("Group", "default") => "Пользователи",
	"" => "Группа &laquo;".$this->group->title."&raquo;",
): array(
	"" => "Пользователи",
);
?>
<? include("header.phtml") ?>

<div id="navigation">
<? include("nav_groups.phtml") ?>
</div>

<div id="contents">
<div id="users">
<? if ($this->group): ?>
	<h2>Пользователи в группе &laquo;<?=$this->group->title?>&raquo; <small>(<?=$this->group->name?>)</small></h2>
    <table class="itemList" summary="Пользователи в группе">
	<thead>
	<tr><th>Имя пользователя</th><th>Логин</th><th>Роль</th><th>Создан</th><th>E-mail</th><th>&nbsp;</th></tr>
	</thead>
	<tbody>
    <? foreach ($this->group->getUsers() as $item): ?>
		<tr id="u<?=$item->getId()?>" class="<?=$item->role?>"><td><a href="<?=$this->pathTo("Admin_User", "edit", array( 'id' => $item->getId() ))?>"><?=$item->username?></a></td><td><?=$item->login?></td><td><?=$item->role?></td><td><?=date("d.m.Y H:i", $item->created)?></td><td><a href="mailto:<?=$item->email?>"><?=$item->email?></a></td><td><a class="remove" href="<?=$this->pathTo("Admin_User", "remove", array( 'id' => $item->getId() ))?>">&nbsp;</a></td></tr>
    <? endforeach ?>
        <tr id="unew"><td colspan="6"><a class="add" href="<?=$this->pathTo("Admin_User", "new", array( 'id' => $this->group->getId() ))?>">Новый пользователь</a></td></tr>
	</tbody>
    </table>
	<?stripe("table tbody tr:odd")?>
<? else: ?>
	<h2>Пользователей в этой группе нет</h2>
<? endif ?>
</div>

</div>

<? include("footer.phtml") ?>
