<?
$this->title = "Список разделов";
$this->topicId = $this->topic? $this->topic->getId(): 0;
?>
<?
$this->breadcrumb = $this->topicId? array(
	$this->pathTo("Topic", "default") => "Контент",
	"" => "Раздел &laquo;".$this->topic->title."&raquo;",
): array(
	"" => "Контент",
);
?>
<? include("header.phtml") ?>
<div id="navigation">
<? include("nav_topics.phtml") ?>
</div>
<div id="contents">

<div id="articles">

<? if ($this->topic): ?>
	<ul class="controls" id="topic-controls">
		<li><a title="Редактировать свойства раздела" class="edit topic" href="<?=$this->pathTo("Topic", "edit", array( 'id' => $this->topicId ))?>">&nbsp;</a></li>
		<li><a title="Удаить раздел" class="remove topic" href="<?=$this->pathTo("Topic", "remove", array( 'id' => $this->topicId ))?>">&nbsp;</a></li>
		<li><a title="Создать новый подраздел" class="new topic" href="<?=$this->pathTo("Topic", "new", array( 'id' => $this->topicId ))?>">&nbsp;</a></li>
	</ul>

	<h2>Статьи из раздела &laquo;<?=$this->topic->title?>&raquo; <small>(<?=$this->topic->name?>)</small></h2>

	<div class="description"><?=$this->topic->description?></div>
    <table class="item-list" summary="Статьи из раздела">
		<thead>
		<tr><th style="width: 2em;">&#8470;</th><th>Заголовок</th><th>Название</th><th>Создана / изменена</th><th>Опубликована / архивирована</th><th>&nbsp;</th></tr>
		</thead>
		<tbody>
    <? foreach ($this->topic->getArticles() as $item): ?>
		<tr id="a<?=$item->getId()?>" class="<?=$item->type?> <?=implode(" ", $item->flags)?>"><td class="order"><?=$item->order?></td><td class="title"><a href="<?=$this->pathTo("Admin_Article", "edit", array( 'id' => $item->getId() ))?>"><?=$item->title?></a></td><td class="name"><?=$item->name?></td><td><?=date("d.m.Y H:i", $item->created)?><br /><?=date("d.m.Y H:i", $item->modified)?></td><td><?=date("d.m.Y H:i", $item->published)?><br /><?=date("d.m.Y H:i", $item->archived)?></td><td class="controls"><a class="remove article" href="<?=$this->pathTo("Admin_Article", "remove", array( 'id' => $item->getId() ))?>">&nbsp;</a></td></tr>
    <? endforeach ?>
        <tr id="anew"><td colspan="6" class="controls"><a class="new article" href="<?=$this->pathTo("Admin_Article", "new", array( 'id' => $this->topic->getId() ))?>">Новая статья</a></td></tr>
		</tbody>
    </table>


<ol id="articles-menu" class="context-menu">
	<li class="copy buffer"><a title="Переименовать статью без перезагузки страницы" href="#rename">Переименовать</a></li>
	<li class="cut buffer"><a title="Вырезать статьи для вставки в другой раздел" href="#cut">Вырезать</a></li>
	<li class="remove article separator"><a title="Удалить статьи" href="#remove">Удалить</a></li>
</ol>

	<script type="text/javascript">
		function rename_article(result)
		{
			var $item = $('#a'+result.id);
			if (result.state != 'failed')
			{
				$item.find("td.title > a:first-child").text(result.title).end().find("td.name").text(result.name);
			}
			else
			{
				error_form(result.error, $item);
			}
		}

		function remove_article(result)
		{
			remove_element($("table.item-list tr#a"+result.id));
		}

		$('table.item-list tbody')
			.sortable({ items: 'tr', cancel: 'tr#anew', handle: 'a' })
			.selectable({ filter: 'tr', cancel: 'tr#anew' });
enable_context_menu('table.item-list tbody tr td:nth-child(2) a', '#articles-menu', function(action, item, pos){

	var $href = $(item);
	var $item = $(item).parent().parent();
	var itemid = parseInt($item.attr("id").substring(1));
	if (isNaN(itemid)) itemid = 0;

	switch (action)
	{
	case 'rename':
		var pos = $item.offset();
		pos.top += $href.height();
		$("#rename-topic")
			.attr("action", sitePrefix+"/article/rename/"+itemid)
			.data("ajaxaction", rename_article)
			.css(pos)
			.find("#ttitle").val($href.text()).end()
			.find("#tname").val($item.find("td.name").text()).end()
			.show()
			.find("#ttitle").focus();
		break;
	case 'cut':
		$('table.item-list tbody tr.cut').removeClass('cut');
		$('table.item-list tbody tr.ui-selected').addClass('cut');
		$('.context-menu li.paste').removeClass('disabled');
		$item.addClass('cut');
		break;
	case 'remove':
		ask_question("Точно удалить эту статью?", $href, sitePrefix+"/article/remove/"+itemid, remove_article);
		break;
	}
});
	</script>
<? else: ?>
	<h2>Не выбран раздел</h2>
	<p class="message">&larr; Выберите раздел из левого меню,<br />или <a href="<?=$this->pathTo('Topic', 'new')?>">создайте новый</a> корневой раздел.</p>
<? endif ?>
</div>

</div>

<? include("footer.phtml") ?>
