<div id="topics" class="module-box">
<h2>Разделы</h2>
<ul>
	<li id="troot"><a href="<?=$this->pathTo('Topic')?>">Корень</a>

	<ul>
		<? foreach ($this->topics as $topic): ?>
		<? if ($this->topics->getStep() == 1): ?><ul><? elseif ($this->topics->getStep() < 0): ?><?=str_repeat("</li></ul>", -($this->topics->getStep()))?></li><? elseif (!$this->topics->isFirst()): ?></li><? endif ?>
		<li id="t<?=$topic->getId()?>"<? if ($topic->getId() == $this->topicId): ?> class="active"<?endif?>>
			<a href="<?=$this->pathTo("Admin_Topic", "default", array( 'id' => $topic->getId() ))?>" title="<?=$topic->name?>"><?=$topic->title?></a>
		<? endforeach ?>
		<? if ($this->topics->getLevel() > 1): ?><?=str_repeat("</li></ul>", $this->topics->getLevel()-1)?><? endif ?>
		</li>
	</ul>

	</li>
</ul>
<h2><a href="<?=$this->pathTo("Topic", "trashcan")?>">Корзина</a></h2>
</div>

<ol id="topics-menu" class="context-menu">
	<li class="edit topic"><a title="Открыть полную форму правки раздела" href="#edit">Изменить</a></li>
	<li class="new article"><a title="Создать новую статью в этом разделе" href="#write">Написать</a></li>
	<li class="new topic"><a title="Создать подраздел в этом разделе" href="#create">Создать</a></li>
	<li class="copy buffer"><a title="Переименовать раздел без перезагузки страницы" href="#rename">Переименовать</a></li>
	<li class="cut buffer separator"><a title="Вырезать раздел для вставки в другой в качестве подраздела" href="#cut">Вырезать</a></li>
	<li class="paste buffer disabled"><a title="Поместить вырезанный раздел в этот" href="#paste">Вставить</a></li>
	<li class="remove topic separator"><a title="Удалить раздел" href="#remove">Удалить</a></li>
</ol>

<ol id="root-topic-menu" class="context-menu">
	<li class="new topic"><a title="Создать подраздел в этом разделе" href="#create">Создать</a></li>
	<li class="paste buffer disabled separator"><a title="Поместить вырезанный раздел в этот" href="#paste">Вставить</a></li>
</ol>

<form id="rename-topic" class="popup-form" action="#">
	<h3>&#8963; переименовать</h3>
	<ol>
		<li><label for="ttitle">Заголовок</label><input type="text" value="" id="ttitle" name="title" /></li>
		<li><label for="tname">Название</label><input type="text" value="" id="tname" name="name" /></li>
		<li><input type="reset" value="Отмена" class="reset" /><input type="submit" value="ОК" class="submit" /></li>
	</ol>
</form>

<?=$this->script("manage/nav_topics")?>
