<div id="topics" class="moduleBox">
<h2>Разделы</h2>
<ul>
<? foreach ($this->topics as $topic): ?>
    <? if ($this->topics->getStep() > 0): ?><?=str_repeat("<ul>", $this->topics->getStep())?><? elseif ($this->topics->getStep() < 0): ?><?=str_repeat("</li></ul></li>", -($this->topics->getStep()))?><? elseif (!$this->topics->isFirst()): ?></li><? endif ?>
    <li id="t<?=$topic->getId()?>"<? if ($topic->getId() == $this->topicId): ?> class="active"<?endif?>>
		<a href="<?=$this->pathTo("Admin_Topic", "default", array( 'id' => $topic->getId() ))?>" title="<?=$topic->name?>"><?=$topic->title?></a>
<? endforeach ?>
	<? if ($this->topics->getLevel() > 1): ?><?=str_repeat("</li></ul>", $this->topics->getLevel()-1)?><? endif ?>
    </li>
</ul>
<h2><a href="<?=$this->pathTo("Topic", "trashcan")?>">Корзина</a></h2>
</div>

<ol id="topicsMenu" class="contextMenu" style="display: none;">
<li class="edit"><a title="Открыть полную форму правки раздела" href="#edit">Изменить</a></li>
<li class="create"><a title="Создать подраздел в этом разделе" href="#create">Создать</a></li>
<li class="rename"><a title="Переименовать раздел без перезагузки страницы" href="#rename">Переименовать</a></li>
<li class="remove"><a title="Удалить раздел" href="#remove">Удалить</a></li>
</ol>

<script type="text/javascript">
$("#topics ul").sortable();
$("#topics ul li a").draggable();
$("#topics ul li a").contextMenu({ menu: 'topicsMenu' },
function (action, item, pos)
{
	var itemid = $(item).parent().attr("id").substring(1);
	switch (action)
	{
	case "edit":
		window.location = "<?=$this->pathTo('Topic', 'edit')?>/"+itemid;
		break;
	case "create":
		window.location = "<?=$this->pathTo('Topic', 'new')?>/"+itemid;
		break;
	case "rename":
		break;
	case "remove":
		break;
	}
});
</script>
