<div id="groups" class="module-box">
<h2>Группы</h2>
<ul>
	<li id="groot"><a href="#">Корень</a>

	<ul>
		<? foreach ($this->groups as $group): ?>
		<? if ($this->groups->getStep() == 1): ?><ul><? elseif ($this->groups->getStep() < 0): ?><?=str_repeat("</li></ul>", -($this->groups->getStep()))?></li><? elseif (!$this->groups->isFirst()): ?></li><? endif ?>
		<li id="g<?=$group->getId()?>"<? if ($group->getId() == $this->groupId): ?> class="active"<?endif?>>
			<a href="<?=$this->pathTo("Admin_Group", "default", array( 'id' => $group->getId() ))?>" title="<?=$group->name?>"><?=$group->title?></a>
		<? endforeach ?>
		<? if ($this->groups->getLevel() > 1): ?><?=str_repeat("</li></ul>", $this->groups->getLevel()-1)?><? endif ?>
		</li>
	</ul>

	</li>
</ul>
</div>
