<div id="groups" class="module-box">
<h2>Группы</h2>
<ul>
	<li id="groot"><a href="#">Корень</a>

	<ul>
		<? foreach ($this->groups as $group): ?>
		<? if ($this->groups->getStep() == 1): ?><ul><? elseif ($this->groups->getStep() < 0): ?><?=str_repeat("</li></ul>", -($this->groups->getStep()))?></li><? elseif (!$this->groups->isFirst()): ?></li><? endif ?>
		<li id="g<?=$group->getId()?>"<? if ($group->getId() == $this->groupId): ?> class="active"<?endif?>>
			<a href="<?=$this->pathTo("Admin_Group", "default", array( 'id' => $group->getId() ))?>" title="<?=$group->name?>"><?=$group->title?></a>
		<? endforeach ?>
		<? if ($this->groups->getLevel() > 1): ?><?=str_repeat("</li></ul>", $this->groups->getLevel()-1)?><? endif ?>
		</li>
	</ul>

	</li>
</ul>
</div>

<ol id="groups-menu" class="context-menu">
	<li class="edit group"><a title="Открыть полную форму правки группы" href="#edit">Изменить</a></li>
	<li class="new user"><a title="Создать пользователя в этой группе" href="#write">Добавить</a></li>
	<li class="new group"><a title="Создать подгруппу в этой группе" href="#create">Создать</a></li>
	<li class="copy buffer"><a title="Переименовать группу без перезагузки страницы" href="#rename">Переименовать</a></li>
	<li class="cut buffer separator"><a title="Вырезать группу для вставки в другую в качестве подгруппы" href="#cut">Вырезать</a></li>
	<li class="paste buffer disabled"><a title="Поместить вырезанную группу в эту" href="#paste">Вставить</a></li>
	<li class="remove group separator"><a title="Удалить группу" href="#remove">Удалить</a></li>
</ol>

<script type="text/javascript">
//<!CDATA[
function handle_group_context_menu(action, item, pos)
{
}

enable_context_menu("#groups ul li#groot ul li a", '#groups-menu', handle_group_context_menu);
enable_context_menu("#groups ul li#groot > a", '#root-group-menu', handle_group_context_menu);
//]]>
</script>
